# both postgres and mqtt tests are run in runtime_tests
name: Run All integration Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Run integration Tests - Attempt ${{ matrix.repeat }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repeat: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]  # Run the same job 5 times

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: spin_dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      # Install all the toolchain dependencies
      - name: Install Rust wasm target
        run: rustup target add wasm32-wasip1 wasm32-unknown-unknown

      - uses: goto-bus-stop/setup-zig@v2

      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache-dependency-path: "**/go.sum"

      - uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: '0.37.0'

      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install Grain
        run: |
          wget https://github.com/grain-lang/grain/releases/download/grain-v0.6.6/grain-linux-x64
          chmod +x grain-linux-x64
          mv grain-linux-x64 grain
          echo "$PWD" >> $GITHUB_PATH

      - name: Run Full integration Tests
        run: make test-integration-full
